apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
  - name: alpha
    image: nginx
    env:
    - name: NAME
      value: alpha
  - name: beta
    image: busybox
    command: ["sleep", "1000"]
    env:
    - name: NAME
      value: beta

      
