apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-toleration-pod
  name: nginx-toleration-pod
spec:
  containers:
  - image: nginx:alpine
    name: nginx-pod
  tolerations:
  - key: "env_type"
    operator: "Equal"
    value: "production"
    effect: "NoSchedule"
