apiVersion: v1
kind: Pod
metadata:
  name: non-persistent-redis
  namespace: qa
spec:
  containers:
  - name: imageredis
    image: redis
    volumeMounts:
    - name: app-cache
      mountPath: /data/redis
  volumes:
  - name: app-cache
    emptyDir: {}
