apiVersion: v1
kind: Pod
metadata:
  labels:
    run: app-basic-cm
  name: app-basic-cm-pod
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - env
    image: busybox
    name: app-basic-cm-pod-c
    envFrom:
    - configMapRef:
        name: app-basic-cm
