apiVersion: v1
kind: Pod
metadata:
  labels:
    run: app-basic-cm
  name: app-basic-cm-pod
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - env
    image: busybox
    name: app-basic-cm-pod-c
    env:
    - name: APP_TYPE
      valueFrom:
        configMapKeyRef:
          name: application-configs
          key: app.type
    - name: APP_UI
      valueFrom:
        configMapKeyRef:
          name: application-configs
          key: app.ui
    - name: APP_VALUE
      valueFrom: 
        configMapKeyRef: 
          name: application-configs
          key: app.value
     
