apiVersion: v1
kind: Pod
metadata:
  name: cm-from-file-pod
spec:
  volumes:
  - name: cm-config-file
    configMap:
      name: cm-from-file
      items:
      - key: var.txt
        path: default.conf 
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: cm-config-file
      mountPath: /tmp/
