apiVersion: v1
kind: Pod
metadata:
  name: cm-from-file-pod2
spec:
  volumes:
  - name: cm-config-file
    configMap:
      name: cm-multi-var
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: cm-config-file
      mountPath: /tmp/
