kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv11
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/srv
