apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: pod1c
    image: redis
    volumeMounts:
    - name: temp-dir
      mountPath: /mnt/data
  volumes:
  - name: temp-dir
    emptyDir: {}
