apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: pod2c
    image: redis
    volumeMounts:
    - name: temp-dir
      mountPath: /mnt/data
  volumes:
  - name: temp-dir
    hostPath:
      path: /tmp
