apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secbusybox
  name: secbusybox
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: secbusybox
    securityContext:
      capabilities:
        add: [ "SYS_TIME", "NET_ADMIN" ]
