apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi-pod
  name: multi-pod
spec:
  containers:
  - image: busybox
    name: multi-pod
    command: ["sh","-c","while true; do echo ‘Hi I am from Main container’ >> /var/log/index.html; sleep 5; done"]
    volumeMounts: 
    - name: share-logs
      mountPath: /var/log
  - image: nginx
    name: nginx
    volumeMounts:
    - name: share-logs
      mountPath: /usr/share/nginx/html
  restartPolicy: Never
  volumes:
  - name: share-logs
    emptyDir: {}

