apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test3
  name: test3
spec:
  containers:
  - image: redis
    name: test3
    volumeMounts:
    - name: demo-secret
      mountPath: /secrets
  volumes:
  - name: demo-secret
    secret:
      secretName: file-secret

