apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test2
  name: test2
spec:
  containers:
  - image: redis
    name: test2
    env:
    - name: CREDENTIALS
      valueFrom:
        secretKeyRef:
          name: super-secret
          key: password
