apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test1
  name: test1
spec:
  containers:
  - image: redis
    name: test1
    volumeMounts:
    - name: demo-secret
      mountPath: /secrets
  volumes:
  - name: demo-secret
    secret:
      secretName: super-secret    
