kind: Job
apiVersion: batch/v1
metadata:
  name: job-multiple-instance
spec:
  completions: 5
  template:
    metadata:
      name: kjobm
    spec:
      containers:
      - name: kjobmc
        image: busybox
        command: ["/bin/sh","-c","echo 'Sleeping 5 seconds'; sleep 5"]
      restartPolicy: OnFailure
