apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  serviceAccountName: testsa
  containers:
    - name: mycontainer
      image: alpine:latest
      command:
        - "sh"
        - "-c"
        - "sleep 1000"

