kind: PersistentVolume
apiVersion: v1
metadata:
  name: nfs-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle 
  nfs:
    server: master01
    path: /nfs/share1
