kind: Pod
apiVersion: v1
metadata:
  name: nginx-pvc-pod2
  labels:
    app: nginx
spec:
  containers:
  - image: nginx
    name: nginx-container
    volumeMounts:
    - name: nfs-pvc-volume
      mountPath: /share/nfs2
  volumes:
  - name: nfs-pvc-volume
    persistentVolumeClaim:
      claimName: nfs-pvc
